"""upgrade to postgres

Revision ID: 3244409d9a6d
Revises: 
Create Date: 2025-03-07 09:26:27.137527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3244409d9a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courier_wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk_courier_wallet_courier_id_couriers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('pickup_location', sa.Text(), nullable=False),
    sa.Column('delivery_location', sa.Text(), nullable=False),
    sa.Column('pricing', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'delivered', 'cancelled')"),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk_delivery_courier_id_couriers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_delivery_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('price_per_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk_pricing_courier_id_couriers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_wallet_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wallet')
    op.drop_table('pricing')
    op.drop_table('delivery')
    op.drop_table('courier_wallet')
    op.drop_table('users')
    op.drop_table('couriers')
    # ### end Alembic commands ###
